site_name: S3 Simple Compress ZIP
repo_url: https://github.com/BrunoMesquitaa/s3_simple_compress
repo_name: s3_simple_compress
edit_uri: tree/main/docs

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

watch:
   - s3_compress


plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [./s3_compress]