site_name: S3 Simple Compress ZIP
repo_url: https://github.com/BrunoMesquitaa/s3_simple_compress
repo_name: s3_simple_compress
edit_uri: tree/main/docs

theme:
  name: material
  palette:
    scheme: slate
    primary: black


markdown_extensions:
  - attr_list
  
extra_css:
  - stylesheets/extra.css

watch:
   - s3_compress


plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [./s3_compress]